# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Cryptonite-iOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CryptoSwift'
  pod 'QRCodeReader.swift'

  # Pods for Cryptonite-iOS

  target 'Cryptonite-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cryptonite-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
